version: '3'

services:
  db:
    image: mongo
    ports:
      - 27017
  queue:
    image: nats
    ports:
      - 4222
  chrome:
    image: zenika/alpine-chrome
    ports:
      - 9222
    command: --no-sandbox --remote-debugging-address=0.0.0.0 --remote-debugging-port=9222
  capture:
    image: leveldorado/screenshot
    depends_on:
      - db
      - queue
      - chrome
    command: ./screenshot --database=mongo:27017 --queue=nats://nats:4222 --mode=capture --chrome=localhost:9222
  api:
    image: leveldorado/screenshot
    depends_on:
      - capture
      - queue
      - db
    ports:
      - 9000
    command: ./screenshot --database=mongo:27017 --queue=nats://nats:4222 --mode=api --address=:9000